SET ECHO ON;

SELECT SYSDATE FROM DUAL;

CREATE TABLE ESPECIALIDADE(
    COD_ESPEC NUMBER(3)
        CONSTRAINT pk_cod_espec PRIMARY KEY,
    NOME VARCHAR2(30) NOT NULL,
    OBS VARCHAR2(100)
);

CREATE TABLE CONVENIO(
    COD_CONV VARCHAR2(6)
        CONSTRAINT pk_cod_conv PRIMARY KEY,
    NOME VARCHAR2(20) NOT NULL,
    STATUS NUMBER(1)
        CONSTRAINT ck_status CHECK (STATUS IN(0, 1, 2))
);


CREATE TABLE MEDICO(
    COD_MED NUMBER(4)
        CONSTRAINT pk_cod_med PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    TITULO VARCHAR2(10),
    CRM NUMBER(6),
    UF_CRM VARCHAR2(2),
    COD_ESPEC NUMBER(3) NOT NULL
    CONSTRAINT uk_med_crm 
        UNIQUE(
                CRM, UF_CRM
        ),
    CONSTRAINT fk_med_espec
        FOREIGN KEY (COD_ESPEC)
        REFERENCES especialidade (COD_ESPEC)
);

CREATE TABLE PACIENTE(
    COD_PAC NUMBER(7) 
        CONSTRAINT pk_cod_pac PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    DT_NASC DATE NOT NULL,
    SEXO VARCHAR(1) NOT NULL
        CONSTRAINT ck_sexo CHECK(SEXO IN('F', 'M')),
    COD_CONV VARCHAR2(6) 
        CONSTRAINT fk_cod_conv REFERENCES CONVENIO,
    HISTORICO VARCHAR2(4000)
);


CREATE TABLE ATENDIMENTO(
    COD_PAC NUMBER(7), 
    COD_MED NUMBER(4),
    DT_ATEND DATE,
    DT_RETORNO DATE,
    PRECO NUMBER(7,2) 
        CONSTRAINT ck_preco_atend CHECK (PRECO >= 0),
    OBS VARCHAR2(500),
    CONSTRAINT pk_atend
        PRIMARY KEY (COD_PAC, COD_MED, DT_ATEND),
    CONSTRAINT fk_atend_pac
        FOREIGN KEY(COD_PAC)
        REFERENCES paciente (COD_PAC),
    CONSTRAINT fk_atend_med
        FOREIGN KEY (COD_MED)
        REFERENCES medico (COD_MED)
);
