SET ECHO ON;
 
SELECT sysdate FROM dual;
 
CREATE TABLE AUTOR(
    COD_NUMBER NUMBER(6) 
        CONSTRAINT pk_autor PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    SEXO VARCHAR2(1) NOT NULL 
        CONSTRAINT ck_sexo_f_m CHECK (SEXO = 'F' OR SEXO = 'M'),
    OBS VARCHAR2(100)
);
 
CREATE TABLE LIVRO(
    COD_LIVRO NUMBER(7) 
        CONSTRAINT pk_cod_livro PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL, 
    ISBN NUMBER(13) 
        CONSTRAINT uk_isbn UNIQUE,
    DT_EDICAO DATE NOT NULL,
    PRECO NUMBER(6,2) 
        CONSTRAINT ck_preco CHECK(PRECO >= 0)    
);
 
CREATE TABLE AUTORIA(
    COD_LIVRO NUMBER(7) 
        CONSTRAINT fk1 REFERENCES LIVRO,
    COD_AUTOR NUMBER(6) 
        CONSTRAINT fk2 REFERENCES AUTOR,
        CONSTRAINT pk_autoria
            PRIMARY KEY(COD_LIVRO,
                        COD_AUTOR)
);
 
 
INSERT INTO AUTORIA VALUES (1,1);

ALTER TABLE AUTOR
MODIFY OBS VARCHAR(200);

ALTER TABLE LIVRO
ADD RESENHA VARCHAR2(500);
